### ISSUE TITLE
Instructions followed, still getting error

### ISSUE THREAD

**Issue by waikoo** [laytan/tailwind-sorter.nvim#91]
```
Error detected while processing BufWritePre Autocommands for "*.tsx":
[tailwind-sorter.nvim]: Error during class sorting: node:internal/modules/cjs/loader:1051,   throw err;,   ^, , Error: Cannot find module '/home/boolean/.local/share/nvim/site/pack/packer/start/tailwind-sorter.nv
im/formatter/dist/index.js',     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15),     at Module._load (node:internal/modules/cjs/loader:901:27),     at Function.executeUserEntryPoint [as run
```
I don't have any autocommands for .tsx files.

I used the code snippet for setting it up (packer), I used the setup snippet to allow format on save in a module in the `after` folder, I spun up a .tsx file and it gave me this error.

I tried inserting my node path manually where it says path: node, didn't work, I tried using the config object with autosave being true inside my packer config where the plugin gets downloaded, no success.

It would be really neat to have this tool.

Could you help me please?

**Comment by chris-av** [comment]
@waikoo  I had to go into the directory `.local/share/nvim/site/pack/packer/start/tailwind-sorter.nvim/formatter` and run the build manually.

```
npm install
npm run build
```

After that, the tailwind sorter began working on my machine. I guess the config from the readme is not successfully building on our behalf?

**Comment by waikoo** [comment]
@chris-av amazing, thank you very much, it worked! i could've never figured it out.

**Comment by laytan** [comment]
Strange, I don't use packer myself but looking at their readme and my readme it seems like the correct setup, using `'run' = 'cd formatter && npm i && npm run build'` it should build the formatter on install

**Comment by anhari** [comment]
Just wanted to chime in and say I ran into a similar error (`cannot find module tailwind-sorter.nvim/formatter`) with the following lazy config. Got it working by running `npm ci && npm run build` in `~/.local/share/nvim/lazy/tailwind-sorter.nvim/formatter` though and it's working great!

```lua
{
    "laytan/tailwind-sorter.nvim",
    dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-lua/plenary.nvim" },
    build = "cd formatter && npm ci && npm run build",
    config = function()
	require("tailwind-sorter").setup({
		on_save_enabled = true, -- If `true`, automatically enables on save sorting.
		on_save_pattern = {
			"*.html",
			"*.js",
			"*.jsx",
			"*.tsx",
			"*.twig",
			"*.hbs",
			"*.php",
			"*.heex",
			"*.astro",
		}, -- The file patterns to watch and sort.
		node_path = "node",
	})
end,
}
```
